openapi: 3.0.0
info:
  title: API spec
  description: API spec
  version: 0.1.0
paths:
  /api/v1/checkins:
    get:
      summary: List all checkIns
      responses:
        200:
          description: Response successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CheckIn'
    post:
      summary: Add a checkIn
      responses:
        201:
          description: Response successful
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    CheckIn:
      type: object
      required:
        - date
        - mood
        - feelings
        - comment
      properties:
        date:
          type: string
        mood:
          type: number
        feelings:
          type: array
          items:
            type: string
        comment:
          type: string
